### ISSUE TITLE
fix: data_class Macro Fails to Generate Code

### ISSUE THREAD

**Issue by KittipongTheothaisong** [felangel/data_class#34] opened 2024-07-01 05:54 UTC
**Description**
data_class macro does not work.

**Steps To Reproduce**

1. Install [FVM](https://fvm.app/documentation/getting-started/installation)
2. Install flutter
Run ```fvm install 3.23.0-0.1.pre```

3. Enable flutter global version
Run ```fvm global 3.23.0-0.1.pre```

4. Create flutter app
Run ```fvm flutter create poc_data_class```

5. Add config to file analysis_options.yaml
```
analyzer:
  enable-experiment:
    - macros
```

6. Add package "data_class"
Run ``` fvm flutter add data_class```

7. Add package "json" (to proof macro is work)
Run ``` fvm flutter add json```

8. Add file temp.dart to /lib
```dart
import 'package:data_class/data_class.dart';
import 'package:json/json.dart';

@JsonCodable()
class Location {
  final double latitude;
  final double longitude;
}

@Data()
class Person {
  final String name;
}

void test() {
  final location = Location.fromJson({});

  const dash = Person(name: 'Dash');
  final sparky = dash.copyWith(name: 'Sparky');
}

```

**Expected Behavior**
Constructor and copyWith functions should work.

**Actual Behavior**
Error when create Person and use copyWith.

**Screenshots**
lib/temp.dart
![Screenshot 2567-07-01 at 13 00 34](https://github.com/felangel/data_class/assets/164855990/27eab208-f4ae-43ce-9974-94c2e3423f2c)

pubspec.yaml
![Screenshot 2567-07-01 at 12 44 04](https://github.com/felangel/data_class/assets/164855990/a5a57dbf-e944-4ef3-adef-0fd42a3657d2)

**Additional Context**
fvm flutter --version
```
Flutter 3.23.0-14.0.pre.76 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1c9c375e4e (18 hours ago) • 2024-06-30 07:43:26 -0400
Engine • revision 0d93da7e2f
Tools • Dart 3.5.0 (build 3.5.0-318.0.dev) • DevTools 2.37.0
```

**Comment by p4-k4** [comment] 2024-07-05 10:40
Any traction on this? Thanks

**Comment by felangel** [comment] 2024-07-05 14:18
I’ll take a closer look shortly 👍

**Comment by felangel** [comment] 2024-07-05 17:31
@p4-k4 @KittipongTheothaisong I just took a look and wasn't able to reproduce the issue using the current `master` channel.

**main.dart**
```dart
import 'package:data_class/data_class.dart';
import 'package:json/json.dart';

@JsonCodable()
class Location {
  final double latitude;
  final double longitude;
}

@Data()
class Person {
  final String name;
}

void main() {
  final location = Location.fromJson({
    'latitude': 0.0,
    'longitude': 0.0,
  });
  print('location: ${location.latitude}, ${location.longitude}');

  const dash = Person(name: 'Dash');
  final sparky = dash.copyWith(name: 'Sparky');
  print(sparky);
}
```

Run with: `dart --enable-experiment=macros run example/main.dart` produced:

```
location: 0.0, 0.0
Person(name: Sparky)
```

```sh
$ dart --version                                       
Dart SDK version: 3.5.0-323.0.dev (dev) (Tue Jul 2 06:25:57 2024 -0700) on "macos_arm64"
```

**Comment by p4-k4** [comment] 2024-07-07 23:58
@felangel  I done a bit of investigation into this. This was on master branch.

What I discovered, at least in my case, is that the dart analyzer is not aware of definitions for libraries outside of the official macro package, meaning definitions are not recognized by the analyzer for 3rd party packages. I confirmed this also by running the project which runs fine with macros, pointing to an analyzer issue.

I also tested this and found it to be true for freezed (dev version), macrotic and this package. The official json package however works fine.

There's a clunky workaround where if you add the package to your project, the analyzer will detect the definitions, not ideal though. @felangel have you experienced this issue?

**Comment by felangel** [comment] 2024-07-08 15:28
> @felangel I done a bit of investigation into this. This was on master branch.
> 
> What I discovered, at least in my case, is that the dart analyzer is not aware of definitions for libraries outside of the official macro package, meaning definitions are not recognized by the analyzer for 3rd party packages. I confirmed this also by running the project which runs fine with macros, pointing to an analyzer issue.
> 
> I also tested this and found it to be true for freezed (dev version), macrotic and this package. The official json package however works fine.
> 
> There's a clunky workaround where if you add the package to your project, the analyzer will detect the definitions, not ideal though. @felangel have you experienced this issue?

Yup this is a duplicate of https://github.com/dart-lang/sdk/issues/55670 and is due to the experimental state of macros at the moment. Closing for now since there's nothing to be done in the `data_class` library as far as I can tell.

**Closed as completed by felangel** 2024-07-08 15:28 UTC
Labels: bug, question
