### ISSUE TITLE
fix: analyser throws errors but runs fine with example code

### ISSUE THREAD

**Issue by azeldaniel** [felangel/data_class#33] opened 2024-06-25 23:47 UTC
**Description**
When experimenting with the example in the README, both VSCode and IntelliJ editors throw syntax errors on my machines. The errors are not affected by the contents of the analysis_options.yaml file. It seems as though the macro is not being registered. Macros from other libraries such as [json](https://pub.dev/packages/json/versions/0.20.0) work fine.

**Steps To Reproduce**

1. Copy example from [README](https://pub.dev/packages/data_class) and place into new dart project.
2. Add dependency for data_class and update analysis_options.yaml
3. Run dart pub get
4. **See error in editor**
5. Code runs fine in terminal

**Expected Behavior**
No syntax errors in editor. Option to view augmented code.

**Screenshots**
Errors in VSCode
<img width="567" alt="Screenshot 2024-06-25 at 7 31 33 PM" src="https://github.com/felangel/data_class/assets/42488313/2c162bef-27dc-4378-b201-39a60ca1d869">

<img width="851" alt="Screenshot 2024-06-25 at 7 31 53 PM" src="https://github.com/felangel/data_class/assets/42488313/3c728d13-5e91-410e-954b-d73502608dc1">

Output
<img width="573" alt="Screenshot 2024-06-25 at 7 45 39 PM" src="https://github.com/felangel/data_class/assets/42488313/c4d3d27c-7cdb-4393-b957-798d072ea144">

**Additional Context**
Flutter version
<img width="580" alt="Screenshot 2024-06-25 at 7 39 18 PM" src="https://github.com/felangel/data_class/assets/42488313/008432bf-18fc-4c5d-8445-43e2418d5285">

Pubspec
<img width="405" alt="Screenshot 2024-06-25 at 7 41 15 PM" src="https://github.com/felangel/data_class/assets/42488313/6b621304-bf99-41aa-af67-2b819d6bad95">

Analysis Options
<img width="402" alt="Screenshot 2024-06-25 at 7 46 33 PM" src="https://github.com/felangel/data_class/assets/42488313/cc7eef55-edd5-4cbd-88bc-cf6eee61c53e">

**Comment by felangel** [comment] 2024-06-26 00:12
Hi @azeldaniel 👋 
This is a duplicate of https://github.com/dart-lang/sdk/issues/55670

**Closed as completed** 2024-06-26 14:09 UTC
Labels: duplicate
